/* Generated By:JavaCC: Do not edit this line. SQLConstants.java */
package com.mckoi.database.sql;

public interface SQLConstants {

  int EOF = 0;
  int STAR = 7;
  int ASSIGNMENT = 8;
  int EQUALS = 9;
  int GR = 10;
  int LE = 11;
  int GREQ = 12;
  int LEEQ = 13;
  int NOTEQ = 14;
  int DIVIDE = 15;
  int ADD = 16;
  int SUBTRACT = 17;
  int BOOLEAN_LITERAL = 18;
  int NULL_LITERAL = 19;
  int REGEX_LITERAL = 20;
  int DROP = 21;
  int SHOW = 22;
  int ALTER = 23;
  int SELECT = 24;
  int UPDATE = 25;
  int CREATE = 26;
  int DELETE = 27;
  int INSERT = 28;
  int COMMIT = 29;
  int COMPACT = 30;
  int EXPLAIN = 31;
  int ROLLBACK = 32;
  int OPTIMIZE = 33;
  int DESCRIBE = 34;
  int SHUTDOWN = 35;
  int IS = 36;
  int AS = 37;
  int ON = 38;
  int IF = 39;
  int ALL = 40;
  int ANY = 41;
  int SET = 42;
  int USE = 43;
  int ASC = 44;
  int NEW = 45;
  int SQLADD = 46;
  int BOTH = 47;
  int SOME = 48;
  int FROM = 49;
  int LEFT = 50;
  int DESC = 51;
  int INTO = 52;
  int JOIN = 53;
  int TRIM = 54;
  int VIEW = 55;
  int COUNT = 56;
  int WHERE = 57;
  int RIGHT = 58;
  int TABLE = 59;
  int LIMIT = 60;
  int INNER = 61;
  int INDEX = 62;
  int CROSS = 63;
  int OUTER = 64;
  int CHECK = 65;
  int USING = 66;
  int UNION = 67;
  int EXCEPT = 68;
  int IGNORE = 69;
  int SCHEMA = 70;
  int EXISTS = 71;
  int VALUES = 72;
  int HAVING = 73;
  int UNIQUE = 74;
  int SQLCOLUMN = 75;
  int LEADING = 76;
  int NATURAL = 77;
  int BETWEEN = 78;
  int TRIGGER = 79;
  int SQLDEFAULT = 80;
  int TRAILING = 81;
  int GROUPBY = 82;
  int ORDERBY = 83;
  int DEFERRED = 84;
  int DISTINCT = 85;
  int IMMEDIATE = 86;
  int INITIALLY = 87;
  int TEMPORARY = 88;
  int INTERSECT = 89;
  int CONSTRAINT = 90;
  int DEFERRABLE = 91;
  int REFERENCES = 92;
  int PRIMARY = 93;
  int FOREIGN = 94;
  int KEY = 95;
  int INDEX_NONE = 96;
  int INDEX_BLIST = 97;
  int GROUPMAX = 98;
  int BIT = 99;
  int INT = 100;
  int REAL = 101;
  int BLOB = 102;
  int CHAR = 103;
  int TEXT = 104;
  int DATE = 105;
  int TIME = 106;
  int FLOAT = 107;
  int BIGINT = 108;
  int DOUBLE = 109;
  int STRING = 110;
  int BINARY = 111;
  int NUMERIC = 112;
  int DECIMAL = 113;
  int BOOLEAN = 114;
  int TINYINT = 115;
  int INTEGER = 116;
  int VARCHAR = 117;
  int SMALLINT = 118;
  int VARBINARY = 119;
  int TIMESTAMP = 120;
  int JAVA_OBJECT = 121;
  int LONGVARCHAR = 122;
  int LONGVARBINARY = 123;
  int TRANSACTIONISOLATIONLEVEL = 124;
  int AUTOCOMMIT = 125;
  int READCOMMITTED = 126;
  int READUNCOMMITTED = 127;
  int REPEATABLEREAD = 128;
  int SERIALIZABLE = 129;
  int NO_ACTION = 130;
  int CASCADE = 131;
  int SET_NULL = 132;
  int SET_DEFAULT = 133;
  int LIKE = 134;
  int REGEX = 135;
  int AND = 136;
  int OR = 137;
  int IN = 138;
  int NOT = 139;
  int NUMBER_LITERAL = 140;
  int STRING_LITERAL = 141;
  int QUOTED_VARIABLE = 142;
  int IDENTIFIER = 143;
  int DOT_DELIMINATED_REF = 144;
  int QUOTED_DELIMINATED_REF = 145;
  int JAVA_OBJECT_ARRAY_REF = 146;
  int CTALIAS = 147;
  int GLOBVARIABLE = 148;
  int QUOTEDGLOBVARIABLE = 149;
  int PARAMETER_REF = 150;
  int LETTER = 151;
  int DIGIT = 152;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"*\"",
    "\"=\"",
    "\"==\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "<NOTEQ>",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "<BOOLEAN_LITERAL>",
    "\"null\"",
    "<REGEX_LITERAL>",
    "\"drop\"",
    "\"show\"",
    "\"alter\"",
    "\"select\"",
    "\"update\"",
    "\"create\"",
    "\"delete\"",
    "\"insert\"",
    "\"commit\"",
    "\"compact\"",
    "\"explain\"",
    "\"rollback\"",
    "\"optimize\"",
    "\"describe\"",
    "\"shutdown\"",
    "\"is\"",
    "\"as\"",
    "\"on\"",
    "\"if\"",
    "\"all\"",
    "\"any\"",
    "\"set\"",
    "\"use\"",
    "\"asc\"",
    "\"new\"",
    "\"add\"",
    "\"both\"",
    "\"some\"",
    "\"from\"",
    "\"left\"",
    "\"desc\"",
    "\"into\"",
    "\"join\"",
    "\"trim\"",
    "\"view\"",
    "\"count\"",
    "\"where\"",
    "\"right\"",
    "\"table\"",
    "\"limit\"",
    "\"inner\"",
    "\"index\"",
    "\"cross\"",
    "\"outer\"",
    "\"check\"",
    "\"using\"",
    "\"union\"",
    "\"except\"",
    "\"ignore\"",
    "\"schema\"",
    "\"exists\"",
    "\"values\"",
    "\"having\"",
    "\"unique\"",
    "\"column\"",
    "\"leading\"",
    "\"natural\"",
    "\"between\"",
    "\"trigger\"",
    "\"default\"",
    "\"trailing\"",
    "\"group by\"",
    "\"order by\"",
    "\"deferred\"",
    "\"distinct\"",
    "\"immediate\"",
    "\"initially\"",
    "\"temporary\"",
    "\"intersect\"",
    "\"constraint\"",
    "\"deferrable\"",
    "\"references\"",
    "\"primary\"",
    "\"foreign\"",
    "\"key\"",
    "\"index_none\"",
    "\"index_blist\"",
    "\"group max\"",
    "\"bit\"",
    "\"int\"",
    "\"real\"",
    "\"blob\"",
    "\"char\"",
    "\"text\"",
    "\"date\"",
    "\"time\"",
    "\"float\"",
    "\"bigint\"",
    "\"double\"",
    "\"string\"",
    "\"binary\"",
    "\"numeric\"",
    "\"decimal\"",
    "\"boolean\"",
    "\"tinyint\"",
    "\"integer\"",
    "\"varchar\"",
    "\"smallint\"",
    "\"varbinary\"",
    "\"timestamp\"",
    "\"java_object\"",
    "\"longvarchar\"",
    "\"longvarbinary\"",
    "\"transaction isolation level\"",
    "\"auto commit\"",
    "\"read committed\"",
    "\"read uncommitted\"",
    "\"repeatable read\"",
    "\"serializable\"",
    "\"no action\"",
    "\"cascade\"",
    "\"set null\"",
    "\"set default\"",
    "\"like\"",
    "\"regex\"",
    "\"and\"",
    "\"or\"",
    "\"in\"",
    "\"not\"",
    "<NUMBER_LITERAL>",
    "<STRING_LITERAL>",
    "<QUOTED_VARIABLE>",
    "<IDENTIFIER>",
    "<DOT_DELIMINATED_REF>",
    "<QUOTED_DELIMINATED_REF>",
    "<JAVA_OBJECT_ARRAY_REF>",
    "<CTALIAS>",
    "<GLOBVARIABLE>",
    "<QUOTEDGLOBVARIABLE>",
    "\"?\"",
    "<LETTER>",
    "<DIGIT>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
  };

}
